### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by 422** [h5bp/mothereffinganimatedgif#45]
Just playing with the scripts, and download link never displays for us.

Also , can we not write the created gifs to our own directory and do away with saveasbro.com ?

Not entirely sure what the saveasbro.com is... aside from analytic gathering

On src inspection, download link always has display:none 

Apologies for sounding like a total tit.

**Comment by arthurvr** [comment]
>  Maybe I'll try to get a pull request across sometime...

@anubiann00b Are you still interested?

**Comment by anubiann00b** [comment]
Sure! It looks like I just need to add the button, make the model, and CSS it.

Quick questions:

 * How do you download a file? Looking at [this StackOverflow answer](http://stackoverflow.com/a/3916267) right now.
 * What datatype is `omgAnimatedGIF` [here](https://github.com/h5bp/mothereffinganimatedgif/blob/4fe38aeff8c88b02a1340a012ffc8b1a5565a6ac/assets/js/ui.js#L46)?

**Comment by paulirish** [comment]
fixed by #69
