### ISSUE TITLE
no license

### ISSUE THREAD

**Issue by twocs** [h5bp/mothereffinganimatedgif#56]
I want to make a html5 animated gif desktop app but no license for this project means unclear copyright terms.

**Comment by arthurvr** [comment]
@paulirish WDYT?

**Comment by twocs** [comment]
Seems that Windows 8 Apps don't support drag-and-drop. Folders are on the Desktop, a separate space from an app. A Windows desktop app version of this project could work, but we can also simply save the web page to use it offline whenever we want.
