### ISSUE TITLE
If you visit the website in a browser without ad blocker goes to spam websites! 

### ISSUE THREAD

**Issue by mohsen1** [h5bp/mothereffinganimatedgif#64]
Possibly everyone has an ad blocker that didn't notice this but visiting http://mothereffinganimatedgif.com/ will get redirected to http://saveasbro.com/ that is a spam website I believe

**Comment by Walkman100** [comment]
In Firefox 43 with AdBlock Plus and HTTPS Everywhere after the page showing the actual content for a few seconds I get redirected to http://saveasbro.com/?folio=9PO7H2L51&rfolio=9POK8A16O, which is a blank page - probably because of AdBlock Plus.

**Comment by Walkman100** [comment]
Same result with the DotNet WebBrowser (which I believe uses the IE engine), and with Safari 5.1.7 on Windows (yes I know)

**Comment by coliff** [comment]
I can reproduce this issue on iPad using safari too. I'll look into why/how it's happening..
