### ISSUE TITLE
Moving domain to ghpages

### ISSUE THREAD

**Issue by paulirish** [h5bp/mothereffinganimatedgif#70]
cloudflare is set up but pointing via CNAME to github pages.

https://mothereffinganimatedgif.com/

if you see saveasbro issues in the console then it hasn't been updated. But i _THINK_ i have the configuration of everything set up... just waiting for propagation..

**Comment by coliff** [comment]
nice. I was going to suggest moving this site to HTTPS...

The only console error I see is that its missing a favicon so will open a separate issue for that.

**Comment by paulirish** [comment]
yup!  

i think the propagation finished now. we good!
